languageCode = "en-gb"
theme = "beautifulhugo"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "https://ganga.dev"
title = "ğŸ’» ğŸš´ğŸ¾â€"
author = "Christopher Ganga"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
googleAnalytics = "UA-135762413-1"
disqusShortname = "gangac"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
    subtitle = "Probably duplicate web content"
    logo = "images/avatar.png"
    favicon = "images/favicon.ico"
    dateFormat = "January 2, 2006"
    commit = true
    rss = true
    socialShare = true
    comments = true
    readingTime = true

[Author]
  name = "Christopher Ganga"
  email = "c@ganga.dev"
  github = "gangachris"
  twitter = "gangachris_"
  stackoverflow = "users/2234099/ganga"
  linkedin = "gangachris"
  spotify = "gangachris"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "External"
    url = "/page/external"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4
